Repository NUTFes/SeeFT, pull requests merged in 2024-09, with the labels that each got.

#90 [fix]データがない場合でも動くように修正（ユーザ、タスク、場所画面）
  admin/next-project/seeft-admin/src/pages/places/index.tsx
  admin/next-project/seeft-admin/src/pages/tasks/add-task/index.tsx
  admin/next-project/seeft-admin/src/pages/tasks/index.tsx
  admin/next-project/seeft-admin/src/pages/users/index.tsx
Labels: frontend

#94 シフトのAPI修正
  admin/next-project/seeft-admin/src/pages/shifts/index.tsx
  api/lib/internals/controller/shift_controller.go
  api/lib/internals/repository/shift_repository.go
  api/lib/router/router.go
  api/lib/usecase/shift_usecase.go
Labels: frontend, backend

#96 [feat]シフトのAPIのデータ削減
  admin/next-project/seeft-admin/src/pages/shifts/index.tsx
  api/lib/internals/controller/shift_controller.go
  api/lib/internals/repository/shift_repository.go
  api/lib/router/router.go
  api/lib/usecase/shift_usecase.go
Labels: frontend, backend

#100 [feat]シフトを表示する高さをscreenに変更
  admin/next-project/seeft-admin/src/pages/shifts/index.tsx
Labels: frontend

#98 [feat]APIをドラッグ後に一斉に動作させるように変更
  admin/next-project/seeft-admin/src/pages/shifts/index.tsx
Labels: frontend

#101 [Feat]シフト編集画面のバグ修正
  admin/next-project/seeft-admin/src/pages/shifts/index.tsx
  api/lib/internals/controller/shift_controller.go
  api/lib/internals/repository/shift_repository.go
  api/lib/router/router.go
  api/lib/usecase/shift_usecase.go
Labels: frontend, backend

#102 [Fix]集合場所の表示バグ修正
  admin/next-project/seeft-admin/src/pages/tasks/index.tsx
  api/lib/di/di.go
  api/lib/entity/shift.go
  api/lib/entity/task.go
  api/lib/usecase/shift_usecase.go
Labels: backend

#103 [feat]タスクの名前でのソート実装
  admin/next-project/seeft-admin/src/pages/shifts/index.tsx
  admin/next-project/seeft-admin/src/pages/tasks/index.tsx
Labels: frontend
